"""Shared LLM endpoint/route registry core."""

from __future__ import annotations

from graph_agent_gateway.registry.contracts import (
    CredentialDescriptor,
    CredentialProviderProtocol,
    SecretLifetimePolicy,
    SnapshotVersion,
    TerminalRetryPolicy,
)
from graph_agent_gateway.registry.credentials import (
    EndpointCredentialProvider,
    FallbackCredentialProvider,
)
from graph_agent_gateway.registry.endpoints import (
    EndpointStandardizationResult,
    ProtocolProbeResult,
    RawProviderEndpointInput,
    canonical_endpoint_id_base,
    legacy_v3_endpoint_id,
    standardize_endpoint_candidates,
)
from graph_agent_gateway.registry.schema import (
    CapabilityValue,
    EffectiveRuntimeSetting,
    EndpointCandidate,
    EvidenceRecord,
    FieldSource,
    LintResult,
    ModelProfile,
    ProbeResult,
    ProviderEndpoint,
    ProviderImportDraft,
    ProviderRoute,
    ReasoningSettings,
    RegistrySnapshot,
    ResolvedRole,
    ResolvedRoute,
    RoleEntry,
    RoleRouteEntry,
    RouteCandidate,
    RuntimePolicy,
    RuntimeSettings,
    StructuredOutputSettings,
    VerifiedProfile,
)

__all__ = [
    "CapabilityValue",
    "CredentialDescriptor",
    "CredentialProviderProtocol",
    "EffectiveRuntimeSetting",
    "EndpointCandidate",
    "EvidenceRecord",
    "EndpointCredentialProvider",
    "EndpointStandardizationResult",
    "FallbackCredentialProvider",
    "FieldSource",
    "LintResult",
    "ModelProfile",
    "ProbeResult",
    "ProviderEndpoint",
    "ProviderImportDraft",
    "ProviderRoute",
    "ProtocolProbeResult",
    "RawProviderEndpointInput",
    "RegistrySnapshot",
    "ResolvedRole",
    "ResolvedRoute",
    "RuntimeSettings",
    "ReasoningSettings",
    "RoleEntry",
    "RoleRouteEntry",
    "RouteCandidate",
    "RuntimePolicy",
    "StructuredOutputSettings",
    "SecretLifetimePolicy",
    "SnapshotVersion",
    "TerminalRetryPolicy",
    "VerifiedProfile",
    "canonical_endpoint_id_base",
    "legacy_v3_endpoint_id",
    "standardize_endpoint_candidates",
]
