"""Shared LLM endpoint/route registry core."""

from __future__ import annotations

from graph_agent_gateway.registry.schema import (
    CapabilityValue,
    EffectiveRuntimeSetting,
    EndpointCandidate,
    FieldSource,
    LintResult,
    ModelProfile,
    ProbeResult,
    ProviderEndpoint,
    ProviderImportDraft,
    ProviderRoute,
    ReasoningSettings,
    RegistrySnapshot,
    ResolvedRole,
    ResolvedRoute,
    RoleEntry,
    RoleRouteEntry,
    RouteCandidate,
    RuntimePolicy,
    RuntimeSettings,
    StructuredOutputSettings,
    VerifiedProfile,
)

__all__ = [
    "CapabilityValue",
    "EffectiveRuntimeSetting",
    "EndpointCandidate",
    "FieldSource",
    "LintResult",
    "ModelProfile",
    "ProbeResult",
    "ProviderEndpoint",
    "ProviderImportDraft",
    "ProviderRoute",
    "RegistrySnapshot",
    "ResolvedRole",
    "ResolvedRoute",
    "RuntimeSettings",
    "ReasoningSettings",
    "RoleEntry",
    "RoleRouteEntry",
    "RouteCandidate",
    "RuntimePolicy",
    "StructuredOutputSettings",
    "VerifiedProfile",
]
